apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata:
  name: pod-delete
  namespace: chaos-demo
  labels:
    name: pod-delete
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups: [""]
        resources: ["pods", "events"]
        verbs: ["create", "list", "get", "patch", "update", "delete", "watch"]
      - apiGroups: ["apps"]
        resources: ["deployments", "replicasets"]
        verbs: ["list", "get"]
    image: litmuschaos/go-runner:1.15.0
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash"]
    args: ["-c", "./experiments -name pod-delete"]
    env:
      - name: TOTAL_CHAOS_DURATION
        value: "30"
      - name: CHAOS_INTERVAL
        value: "10"
      - name: PODS_AFFECTED_PERC
        value: "33"
