apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: pod-delete-engine
  namespace: chaos-demo
spec:
  annotationCheck: 'false'
  appinfo:
    appns: chaos-demo
    applabel: app=demo
    appkind: deployment
  chaosServiceAccount: litmus
  monitoring: 'false'
  jobCleanUpPolicy: 'delete'
  experiments:
    - name: pod-delete
      spec:
        components: {}
